from typing import BinaryIO
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.exceptions import InvalidTag


class AESGCMEncryptionError(Exception):
    """Raised when an unexpected error occurs during streaming encryption."""
    pass


class AESGCMDecryptionError(Exception):
    """Raised when decryption fails, typically due to an invalid Auth Tag (tampering)."""
    pass


class AESManager:
    """
    Provides memory-safe, streaming encryption and decryption using AES-256-GCM.
    
    Responsibilities:
    - Encrypt and decrypt arbitrarily large files without exhausting RAM.
    - Guarantee data integrity and authenticity via the GCM Authentication Tag.
    - Safely translate low-level cryptographic exceptions into domain errors.
    """
    
    # 64 KB chunk size offers an excellent balance between memory footprint 
    # and CPU context-switching overhead during file I/O operations.
    CHUNK_SIZE = 64 * 1024  

    @staticmethod
    def encrypt_stream(key: bytes, nonce: bytes, in_stream: BinaryIO, out_stream: BinaryIO) -> bytes:
        """
        Encrypts a plaintext stream into a ciphertext stream in chunks.
        
        Args:
            key (bytes): 32-byte (256-bit) ephemeral AES key.
            nonce (bytes): 12-byte (96-bit) cryptographic initialization vector.
            in_stream (BinaryIO): Open, readable binary stream of the source file.
            out_stream (BinaryIO): Open, writable binary stream for the encrypted output.
            
        Returns:
            bytes: The 16-byte Authentication Tag generated by GCM.
            
        Raises:
            AESGCMEncryptionError: If the underlying cipher or I/O fails.
        """
        try:
            # Initialize the cryptographic primitives
            encryptor = Cipher(
                algorithms.AES(key),
                modes.GCM(nonce)
            ).encryptor()
            
            # Stream the data in memory-safe chunks
            while True:
                chunk = in_stream.read(AESManager.CHUNK_SIZE)
                if not chunk:
                    break
                out_stream.write(encryptor.update(chunk))
                
            # Finalize the encryption to extract the Auth Tag
            encryptor.finalize()
            return encryptor.tag
            
        except Exception as e:
            raise AESGCMEncryptionError(f"A critical error occurred during streaming encryption: {e}") from e

    @staticmethod
    def decrypt_stream(key: bytes, nonce: bytes, tag: bytes, in_stream: BinaryIO, out_stream: BinaryIO) -> None:
        """
        Decrypts a ciphertext stream into a plaintext stream in chunks, 
        and cryptographically authenticates the data against tampering.
        
        Args:
            key (bytes): 32-byte (256-bit) ephemeral AES key.
            nonce (bytes): 12-byte (96-bit) initialization vector extracted from the file header.
            tag (bytes): 16-byte Auth Tag extracted from the file header.
            in_stream (BinaryIO): Open, readable binary stream of the encrypted file.
            out_stream (BinaryIO): Open, writable binary stream for the restored plaintext.
            
        Raises:
            AESGCMDecryptionError: If the Auth Tag is invalid (indicating tampering or wrong password).
        """
        try:
            # The decryptor is initialized with the expected Tag upfront
            decryptor = Cipher(
                algorithms.AES(key),
                modes.GCM(nonce, tag)
            ).decryptor()
            
            while True:
                chunk = in_stream.read(AESManager.CHUNK_SIZE)
                if not chunk:
                    break
                out_stream.write(decryptor.update(chunk))
                
            # Finalize enforces the cryptographic signature (Auth Tag).
            # If the derived key is wrong, or the ciphertext was altered, 
            # this explicitly raises cryptography.exceptions.InvalidTag.
            decryptor.finalize()
            
        except InvalidTag:
            # Critical Security Boundary: Catch the specific tampering exception
            raise AESGCMDecryptionError(
                "Authentication failed: The file has been tampered with or the provided password is incorrect."
            )
        except Exception as e:
            raise AESGCMDecryptionError(f"A critical error occurred during streaming decryption: {e}") from e
